"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""
fib = [1, 2]
#evenFib = 2 to account for the 2 in the sequence
evenFib = 2
def isEven(val):
	if(val % 2 == 0):
		return True
	else:
		return False
curr = 1
while(fib[-2] + fib[-1] < 4000000):
	curr = fib[-1] + fib[-2] 
	fib.append(curr)
	if(isEven(curr)):
		evenFib+=curr
print(evenFib)

